// Objective-C API for talking to github.com/OpenNHP/StealthDNS/mobile/golib Go package.
//   gobind -lang=objc github.com/OpenNHP/StealthDNS/mobile/golib
//
// File is generated by gobind. Do not edit.

#ifndef __Nhpcore_H__
#define __Nhpcore_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class NhpcoreQRAuthResult;
@class NhpcoreQRCodeScanResult;

/**
 * QRAuthResult represents the result of QR authentication
 */
@interface NhpcoreQRAuthResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) BOOL success;
@property (nonatomic) NSString* _Nonnull errMsg;
@end

/**
 * QRCodeScanResult represents the parsed QR code data
 */
@interface NhpcoreQRCodeScanResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) BOOL success;
@property (nonatomic) NSString* _Nonnull sessionID;
@property (nonatomic) NSString* _Nonnull token;
@property (nonatomic) NSString* _Nonnull otpSecret;
@property (nonatomic) NSString* _Nonnull aspId;
@property (nonatomic) NSString* _Nonnull resId;
@property (nonatomic) NSString* _Nonnull server;
@property (nonatomic) NSString* _Nonnull errMsg;
@end

/**
 * Constants
 */
FOUNDATION_EXPORT const int64_t NhpcoreDefaultServerPort;
/**
 * Constants
 */
FOUNDATION_EXPORT NSString* _Nonnull const NhpcoreDefaultUpstreamDNS;
/**
 * Constants
 */
FOUNDATION_EXPORT NSString* _Nonnull const NhpcoreNhpDomainSuffix;
/**
 * Constants
 */
FOUNDATION_EXPORT NSString* _Nonnull const NhpcoreVersion;

/**
 * Cleanup releases all resources
 */
FOUNDATION_EXPORT void NhpcoreCleanup(void);

/**
 * ExtractResourceID extracts the resource ID from an NHP domain
e.g., "myapp.nhp" -> "myapp", "securitygroup.nhp" -> "securitygroup"
 */
FOUNDATION_EXPORT NSString* _Nonnull NhpcoreExtractResourceID(NSString* _Nullable domain);

/**
 * GenerateTOTP generates a TOTP code from the secret
secret: the base32 encoded TOTP secret
 */
FOUNDATION_EXPORT NSString* _Nonnull NhpcoreGenerateTOTP(NSString* _Nullable secret);

/**
 * GetKnockResultJSON performs knock and returns result as JSON
resourceID: the resource ID extracted from domain (e.g., "demo" from "demo.nhp")
Returns JSON with fields matching ServerKnockAckMsg: errCode, errMsg, resHost, opnTime, etc.
 */
FOUNDATION_EXPORT NSString* _Nonnull NhpcoreGetKnockResultJSON(NSString* _Nullable resourceID);

/**
 * InitializeWithConfig initializes the NHP agent with JSON config
configJSON: JSON string containing agent config, servers, and resources
 */
FOUNDATION_EXPORT BOOL NhpcoreInitializeWithConfig(NSString* _Nullable workDir, long logLevel, NSString* _Nullable configJSON, NSError* _Nullable* _Nullable error);

/**
 * IsInitialized returns whether the agent is initialized
 */
FOUNDATION_EXPORT BOOL NhpcoreIsInitialized(void);

/**
 * IsNHPDomain checks if the domain ends with .nhp suffix
 */
FOUNDATION_EXPORT BOOL NhpcoreIsNHPDomain(NSString* _Nullable domain);

/**
 * NotifyQRScan notifies the server that QR code has been scanned
This updates the session status from "pending" to "scanned"
serverUrl: the NHP server URL
sessionId: the QR session ID (extracted from encrypted data or QR content)
aspId: auth service provider ID (plugin ID)
resId: resource ID
 */
FOUNDATION_EXPORT NSString* _Nonnull NhpcoreNotifyQRScan(NSString* _Nullable serverUrl, NSString* _Nullable sessionId, NSString* _Nullable aspId, NSString* _Nullable resId);

/**
 * ParseQRCodeData parses the QR code content and returns structured data
qrContent: the raw QR code content (e.g., "nhp://scan?data=...&otp=...")
 */
FOUNDATION_EXPORT NSString* _Nonnull NhpcoreParseQRCodeData(NSString* _Nullable qrContent);

/**
 * VerifyQRAuth sends QR authentication verification to the server via GET request
serverUrl: the NHP server URL (e.g., "https://nhp.example.com")
encryptedData: the encrypted QR data
otpCode: the TOTP code generated from the secret
deviceInfo: device information string
aspId: auth service provider ID (plugin ID)
resId: resource ID
 */
FOUNDATION_EXPORT NSString* _Nonnull NhpcoreVerifyQRAuth(NSString* _Nullable serverUrl, NSString* _Nullable encryptedData, NSString* _Nullable otpCode, NSString* _Nullable deviceInfo, NSString* _Nullable aspId, NSString* _Nullable resId);

#endif
