// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearLogFile(arg1:string):Promise<void>;

export function GetAutoRestart():Promise<boolean>;

export function GetClientConfig():Promise<main.ClientConfig>;

export function GetLogContent(arg1:string,arg2:number):Promise<Array<main.LogEntry>>;

export function GetLogFiles():Promise<Array<main.LogFile>>;

export function GetServerConfig():Promise<Array<main.ServerConfig>>;

export function GetStatus():Promise<main.ServiceStatus>;

export function GetSystemDNS():Promise<main.SystemDNSInfo>;

export function MinimizeToTray():Promise<void>;

export function Quit():Promise<void>;

export function RestartDNS():Promise<void>;

export function SaveClientConfig(arg1:main.ClientConfig):Promise<void>;

export function SaveServerConfig(arg1:Array<main.ServerConfig>):Promise<void>;

export function SetAutoRestart(arg1:boolean):Promise<void>;

export function SetTrayManager(arg1:main.TrayManager):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartDNS():Promise<void>;

export function StopDNS():Promise<void>;

export function WatchLogFile(arg1:string,arg2:number):Promise<Array<main.LogEntry>>;
