// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogFile(arg1) {
  return window['go']['main']['App']['ClearLogFile'](arg1);
}

export function GetAutoRestart() {
  return window['go']['main']['App']['GetAutoRestart']();
}

export function GetClientConfig() {
  return window['go']['main']['App']['GetClientConfig']();
}

export function GetLogContent(arg1, arg2) {
  return window['go']['main']['App']['GetLogContent'](arg1, arg2);
}

export function GetLogFiles() {
  return window['go']['main']['App']['GetLogFiles']();
}

export function GetServerConfig() {
  return window['go']['main']['App']['GetServerConfig']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetSystemDNS() {
  return window['go']['main']['App']['GetSystemDNS']();
}

export function MinimizeToTray() {
  return window['go']['main']['App']['MinimizeToTray']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RestartDNS() {
  return window['go']['main']['App']['RestartDNS']();
}

export function SaveClientConfig(arg1) {
  return window['go']['main']['App']['SaveClientConfig'](arg1);
}

export function SaveServerConfig(arg1) {
  return window['go']['main']['App']['SaveServerConfig'](arg1);
}

export function SetAutoRestart(arg1) {
  return window['go']['main']['App']['SetAutoRestart'](arg1);
}

export function SetTrayManager(arg1) {
  return window['go']['main']['App']['SetTrayManager'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartDNS() {
  return window['go']['main']['App']['StartDNS']();
}

export function StopDNS() {
  return window['go']['main']['App']['StopDNS']();
}

export function WatchLogFile(arg1, arg2) {
  return window['go']['main']['App']['WatchLogFile'](arg1, arg2);
}
