
// Objective-C API for talking to the following Go packages
//
//	github.com/OpenNHP/StealthDNS/mobile/golib
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Nhpcore_FRAMEWORK_H__
#define __Nhpcore_FRAMEWORK_H__

#include "Nhpcore.objc.h"
#include "Universe.objc.h"

#endif
